"""add_documents_table

Revision ID: 3681a0c72309
Revises: 8ddff4af3de4
Create Date: 2026-06-25 21:33:34.418055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3681a0c72309'
down_revision: Union[str, None] = '8ddff4af3de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_slug', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('r2_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_slug'], ['public.organizations.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_documents_org_slug'), 'documents', ['org_slug'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_documents_org_slug'), table_name='documents', schema='public')
    op.drop_table('documents', schema='public')
    # ### end Alembic commands ###
